# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 02:42
from __future__ import unicode_literals

from django.db import migrations

def create_foreign_keys(apps, schema_editor):
    Schools = apps.get_model("restapi", "Schools")
    Members = apps.get_model('restapi', "GroupMembers")
    Posts = apps.get_model('restapi', 'Posts')

    for school in Schools.objects.all():
        name = school.school_name
        Members.objects.filter(school=name).update(school_name=name)
        Posts.objects.filter(school=name).update(school_name=name)

def undo(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20171215_0225'),
    ]

    operations = [
        migrations.RunPython(create_foreign_keys, undo)
    ]
