# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affil', models.CharField(blank=True, max_length=250, null=True)),
                ('fb_name', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('school', models.CharField(max_length=15)),
                ('approver_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'group_members',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=15)),
                ('poster_name', models.CharField(max_length=100)),
                ('post_time', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=110, null=True)),
                ('caption', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.CharField(blank=True, max_length=75, null=True)),
                ('num_reacts', models.IntegerField(blank=True, null=True)),
                ('angrys', models.IntegerField(blank=True, null=True)),
                ('hahas', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('loves', models.IntegerField(blank=True, null=True)),
                ('prides', models.IntegerField(blank=True, null=True)),
                ('sads', models.IntegerField(blank=True, null=True)),
                ('thankfuls', models.IntegerField(blank=True, null=True)),
                ('wows', models.IntegerField(blank=True, null=True)),
                ('reacts_url', models.CharField(blank=True, max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('post_date', models.DateField()),
                ('post_hour', models.IntegerField(blank=True, null=True)),
                ('img_hash', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': True,
            },
        )
    ]
