# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
