# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_schools(apps, schema_editor):
    Schools = apps.get_model("restapi", "Schools")
    Members = apps.get_model('restapi', "GroupMembers")
    school_names = Members.objects.values("school").distinct()
    Schools.objects.bulk_create([
        Schools(school_name=s['school']) for s in school_names
    ])

def delete_schools(apps, schema_editor):
    Schools = apps.get_model("restapi", "Schools")
    Schools.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_schools'),
    ]

    operations = [
        migrations.RunPython(create_schools, delete_schools),
        migrations.AddField(
            model_name='groupmembers',
            name='school_name',
            field=models.ForeignKey(default='cornell', on_delete=django.db.models.deletion.CASCADE, related_name='school_attended', to='restapi.Schools', to_field='school_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='school_name',
            field=models.ForeignKey(default='cornell', on_delete=django.db.models.deletion.CASCADE, related_name='school_posted', to='restapi.Schools', to_field='school_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='id',
            field=models.IntegerField(default=1, serialize=False),
        ),
    ]
